version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wrong-notebook
    restart: always
    ports:
      - "3000:3000"
    environment:
      # environment variables defined here take precedence over those in env_file
      # We override DATABASE_URL to ensure it points to the container's internal path
      - DATABASE_URL=file:/app/prisma/dev.db
      # NEXTAUTH_URL will be loaded from .env file
      - NEXTAUTH_SECRET=password
    env_file:
      - .env
    volumes:
      # Persist the SQLite database
      - ./prisma:/app/prisma
      - ./config:/app/config

